### ISSUE TITLE
Unable to Locate the Datasets

### ISSUE THREAD

**Issue by rohitsharma0201** [Shubhammalik/Drug-Review-Analysis-Work#1]
Hello Sir, Are the Datasets missing here? 
I could not find the location of datasets and web files?

**Comment by Shubhammalik** [comment]
Hello Rohit,

Yes, we web scraped the data online so it’s not there in the repo, only the
code will be there.
You might need to run the individual scrapers to get the data, each scraper
takes around 3-4 hours. I can review the data on my local If I have it.
You can share your email and I can forward it to you.

Best,
Shubham

**Comment by Shubhammalik** [comment]
Updated a folder dataset in the repository.
